# IPython log file

runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
get_ipython().run_line_magic('clear', '')
runfile('/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting/ema_rsi_camarilla_back_test.py', wdir='/Users/jegankarunakaran/AlgoTrading/code/AlgoTrading/strategies/ema-rsi-camarilla/backtesting')
